spring:
  application:
    name: springboot-war
  datasource:
#   配置数据库连接信息
    url: jdbc:mysql://127.0.0.1/dmall?zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
#    配置数据源类型,默认为tomcat的
    type: com.alibaba.druid.pool.DruidDataSource
#    连接池相关设置
    initial-size: 5
    min-idle: 5
    max-active: 20
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
#    打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxpoolpreparedstatementperconnectionsize: 20
#      配置监控统计
    filters: stat,wall
#    通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

  redis:
    database: 0
    host: 127.0.0.1
    password: 123456
    port: 6379
    timeout: 4000
    jedis:
      pool:
#      连接池最大连接数(负数表示无限制)  max-active改为以下属性
        max-total: 9
#        最大空闲连接
        max-idle: 9
#        最小控制连接
        min-idle: 0
#        连接池最大阻塞等待时间（使用负值表示没有限制）max-wait 变为以下属性
        max-wait-millis: 2000
#        线程超时时间,超过设置的时间没有结束的话杀掉该线程默认为10000
        evictorShutdownTimeoutMillis: 9000









